"use client";

import { Archive, ArrowRight, Clock3, FilePenLine, Inbox, Plus } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

type Item = { id: string; code: string; title: string; field: string; status: string; submissionStep: number; updatedAt: string; completedAt: string | null; issue: { volume: number; number: number; year: number } | null; _count: { contributors: number; reviews: number } };
const archivedStatuses = new Set(["PUBLISHED", "REJECTED"]);
const statusLabels: Record<string, string> = { DRAFT: "Chưa hoàn tất", SUBMITTED: "Đã nộp", SCREENING: "Sàng lọc", ASSIGNED: "Đã phân công", UNDER_REVIEW: "Đang phản biện", REVISION_REQUESTED: "Yêu cầu sửa", REVISED: "Đã nộp bản sửa", ACCEPTED: "Chấp nhận", REJECTED: "Từ chối", PUBLISHED: "Đã xuất bản" };

export function AuthorDashboard({ manuscripts }: { manuscripts: Item[] }) {
  const [view, setView] = useState<"ongoing" | "archive">("ongoing");
  const filtered = manuscripts.filter((item) => view === "archive" ? archivedStatuses.has(item.status) : !archivedStatuses.has(item.status));
  return <section className="mx-auto grid min-h-[calc(100dvh-var(--site-header-height))] max-w-[1440px] lg:grid-cols-[240px_minmax(0,1fr)]">
    <aside className="border-b border-[#dbe4ee] bg-white p-4 lg:border-b-0 lg:border-r lg:p-6"><p className="text-xs font-extrabold uppercase text-[var(--uel-brand-blue)]">Submission portal</p><nav className="mt-5 grid gap-1"><SideButton active={view === "ongoing"} onClick={() => setView("ongoing")} icon={Inbox} label="Đang xử lý" count={manuscripts.filter((item) => !archivedStatuses.has(item.status)).length} /><SideButton active={view === "archive"} onClick={() => setView("archive")} icon={Archive} label="Lưu trữ" count={manuscripts.filter((item) => archivedStatuses.has(item.status)).length} /></nav></aside>
    <main className="min-w-0 px-4 py-7 md:px-8 lg:py-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="section-kicker">Dashboard tác giả</p><h1 className="mt-2 text-3xl font-extrabold text-[var(--uel-navy)]">Bản thảo của tôi</h1><p className="mt-2 text-sm text-[var(--muted)]">Theo dõi hồ sơ chưa hoàn tất và toàn bộ tiến trình biên tập.</p></div><Link href="/nop-bai" className="inline-flex h-11 items-center gap-2 bg-[var(--uel-brand-blue)] px-4 text-sm font-bold text-white"><Plus size={17} />Nộp bài mới</Link></div>
      <div className="mt-7 panel overflow-hidden"><div className="border-b border-[#dbe4ee] px-5 py-4"><h2 className="uel-block-title text-xl">{view === "ongoing" ? "Đang xử lý" : "Lưu trữ"}</h2></div><div className="divide-y divide-[#e2e8f0]">{filtered.map((item) => <article key={item.id} className="grid gap-4 px-5 py-5 md:grid-cols-[minmax(0,1fr)_180px_130px]"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className={`px-2 py-1 text-[11px] font-bold ${item.status === "DRAFT" ? "bg-[#fff3d6] text-[#8a5a00]" : "bg-[#e8f2ec] text-[#21633d]"}`}>{statusLabels[item.status] ?? item.status}</span><span className="text-xs font-semibold text-[var(--muted)]">{item.code}</span></div><h3 className="mt-2 font-extrabold text-[var(--uel-navy)]">{item.title}</h3><p className="mt-1 text-xs text-[var(--muted)]">{item.field} · {item.issue ? `Tập ${item.issue.volume}, Số ${item.issue.number}/${item.issue.year}` : "Chưa phân số"}</p></div><div className="text-xs text-[var(--muted)]"><p className="flex items-center gap-1.5"><Clock3 size={14} />Cập nhật</p><p className="mt-2 font-bold text-[var(--ink)]">{new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium" }).format(new Date(item.updatedAt))}</p><p className="mt-1">{item._count.contributors} tác giả · {item._count.reviews} phản biện</p></div><div className="flex items-start justify-end">{item.status === "DRAFT" ? <Link href={`/nop-bai?id=${item.id}`} className="inline-flex h-9 items-center gap-2 text-sm font-bold text-[var(--uel-brand-blue)]"><FilePenLine size={16} />Tiếp tục <ArrowRight size={15} /></Link> : <span className="text-xs font-semibold text-[var(--muted)]">Theo dõi tại đây</span>}</div></article>)}{!filtered.length ? <p className="py-16 text-center text-sm text-[var(--muted)]">Chưa có bản thảo trong mục này.</p> : null}</div></div>
    </main>
  </section>;
}
function SideButton({ active, onClick, icon: Icon, label, count }: { active: boolean; onClick: () => void; icon: LucideIcon; label: string; count: number }) { return <button type="button" onClick={onClick} className={`flex h-11 items-center gap-3 border-l-4 px-3 text-sm font-bold ${active ? "border-[var(--uel-gold)] bg-[#edf4fb] text-[var(--uel-brand-blue)]" : "border-transparent text-[var(--muted)] hover:bg-[#f6f8fa]"}`}><Icon size={18} />{label}<span className="ml-auto text-xs">{count}</span></button>; }
